// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBABIIMFjqfsAA32jjq3G2B3Y4MuxwSn9o',
    appId: '1:1063652285590:web:f2f0298c038fa8049776b7',
    messagingSenderId: '1063652285590',
    projectId: 'masrofy-2e63e',
    authDomain: 'masrofy-2e63e.firebaseapp.com',
    storageBucket: 'masrofy-2e63e.firebasestorage.app',
    measurementId: 'G-8VZXHZXK7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgX-0tVw_6E-K3LbPr0ix7cODdRdI3QM',
    appId: '1:1063652285590:android:70b04857e9323d599776b7',
    messagingSenderId: '1063652285590',
    projectId: 'masrofy-2e63e',
    storageBucket: 'masrofy-2e63e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBR6DY4ha4ZMNpGIBLfbY2FTLJy5Z7l8',
    appId: '1:1063652285590:ios:cc56c04ac2be29439776b7',
    messagingSenderId: '1063652285590',
    projectId: 'masrofy-2e63e',
    storageBucket: 'masrofy-2e63e.firebasestorage.app',
    androidClientId: '1063652285590-vt9aoa1gcisfj0h9q7cgodabu6qphtah.apps.googleusercontent.com',
    iosClientId: '1063652285590-t8e7ke97ftm6u67gut28d0svh0jp4qiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoBR6DY4ha4ZMNpGIBLfbY2FTLJy5Z7l8',
    appId: '1:1063652285590:ios:cc56c04ac2be29439776b7',
    messagingSenderId: '1063652285590',
    projectId: 'masrofy-2e63e',
    storageBucket: 'masrofy-2e63e.firebasestorage.app',
    androidClientId: '1063652285590-vt9aoa1gcisfj0h9q7cgodabu6qphtah.apps.googleusercontent.com',
    iosClientId: '1063652285590-t8e7ke97ftm6u67gut28d0svh0jp4qiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBABIIMFjqfsAA32jjq3G2B3Y4MuxwSn9o',
    appId: '1:1063652285590:web:b51f34cdda5984429776b7',
    messagingSenderId: '1063652285590',
    projectId: 'masrofy-2e63e',
    authDomain: 'masrofy-2e63e.firebaseapp.com',
    storageBucket: 'masrofy-2e63e.firebasestorage.app',
    measurementId: 'G-YMQ75SGSB9',
  );
}
